########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the Organization CloudTrail logging S3 bucket

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Organization CloudTrail S3 Attributes
        Parameters:
          - pBucketNamePrefix
          - pOrganizationCloudTrailKMSKey
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pBucketNamePrefix:
        default: Bucket Name Prefix
      pOrganizationCloudTrailKMSKey:
        default: Organization CloudTrail KMS Key ARN
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pBucketNamePrefix:
    AllowedPattern: "^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Description: S3 bucket prefix. The account and region will get added to the end. e.g. bucket-prefix-123456789012-us-east-1
    Default: org-trail-logs
    Type: String

  pOrganizationCloudTrailKMSKey:
    AllowedPattern:
      '^arn:(aws[a-zA-Z-]*)?:kms:[a-z0-9-]+:\d{12}:key\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'
    ConstraintDescription:
      'Key ARN example:  arn:aws:kms:us-east-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab'
    Description: KMS Key ARN to use for encrypting S3 Buckets
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String
    Default: Sumo

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String
    Default: ASPIN2

Resources:
  rOrgTrailBucket:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: S3 access logging covered by CloudTrail S3 data events
    Properties:
      BucketName: !Sub ${pBucketNamePrefix}-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref pOrganizationCloudTrailKMSKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rOrgTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rOrgTrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:

          - Sid: DenyPutObject
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}
              - !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}/*
            Condition:
              ForAnyValue:StringNotEquals:
                aws:CalledVia: cloudtrail.amazonaws.com

          - Sid: SecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}
              - !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}/*
            Condition:
              Bool:
                "aws:SecureTransport": "false"

          - Sid: AWSBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:ListBucket
            Resource: !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}

          - Sid: AWSBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}/*
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"

          # ----------------------------------------------------------------------------
          # These statements prevent creating the Org Trail
          # Uncomment after initial create
          # ----------------------------------------------------------------------------
#          - Sid: DenyUnencryptedObjects
#            Effect: Deny
#            Principal: "*"
#            Action: s3:PutObject
#            Resource: !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}/*
#            Condition:
#              StringNotEquals:
#                "s3:x-amz-server-side-encryption": "aws:kms"
#
#          - Sid: DenyWrongKMSKey
#            Effect: Deny
#            Principal: "*"
#            Action: s3:PutObject
#            Resource: !Sub arn:${AWS::Partition}:s3:::${rOrgTrailBucket}/*
#            Condition:
#              StringNotEquals:
#                "s3:x-amz-server-side-encryption-aws-kms-key-id": !Sub ${pOrganizationCloudTrailKMSKey}


Outputs:
  oOrganizationCloudTrailS3:
    Description: Organization CloudTrail S3 Bucket
    Value: !Ref rOrgTrailBucket